// AUTO-GENERATED by scripts/generate-ubuntu-data.ts — do not edit by hand.

export const strokeWidthRatio = 0.08
export const glyphWidthRatio = 0.5508791086074476
export const spaceWidthRatio = 0.23789907312049433
export const lineHeightRatio = 1.212152420185376
export const letterSpacingRatio = 0
export const capHeight = 0.713697219361483
