// AUTO-GENERATED by scripts/generate-ubuntu-data.ts — do not edit by hand.

export const strokeWidthRatio = 0.05
export const glyphWidthRatio = 0.5400593103619421
export const spaceWidthRatio = 0.23480947476828012
export const lineHeightRatio = 1.212152420185376
export const letterSpacingRatio = 0
export const capHeight = 0.713697219361483
